services:
  postgres:
    image: postgres:17
    env_file: .env
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:8.2
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
       test: ["CMD", "redis-cli","ping"]
    networks:
      - app_network

  backend:
    build: ./backend
    env_file: .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend:delegated
      - /backend/.venv
    networks:
      - app_network

  backend-price-stream:
    build: ./backend
    env_file: .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/true"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend:/backend:delegated
      - /backend/.venv
    networks:
      - app_network
    command: uv run manage.py mock_stream_prices


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
