# Generated by Django 5.2.6 on 2025-12-01 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('volume', models.DecimalField(decimal_places=15, max_digits=30)),
                ('buy_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='transactions.transaction')),
                ('sell_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
