# Generated by Django 5.2.6 on 2025-12-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_partialtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialtransaction',
            name='sell_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='transactions.transaction'),
        ),
    ]
