# Generated by Django 5.2.6 on 2025-12-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_partialtransaction_sell_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialtransaction',
            name='buy_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_buys', to='transactions.transaction', verbose_name='Associated buy transaction'),
        ),
        migrations.AlterField(
            model_name='partialtransaction',
            name='sell_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_sells', to='transactions.transaction', verbose_name='Associated sell transaction'),
        ),
        migrations.AlterField(
            model_name='partialtransaction',
            name='volume',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Volume'),
        ),
    ]
