# Generated by Django 5.2.6 on 2025-11-16 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_notificationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Deposit Amount')),
                ('deposited_at', models.DateTimeField(auto_now_add=True, verbose_name='Deposited At')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='investors.investor', verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Deposit History',
                'verbose_name_plural': 'Deposit Histories',
                'ordering': ['-deposited_at'],
            },
        ),
    ]
