# Generated by Django 5.2.6 on 2025-11-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_notificationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='last_deposited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Deposit At'),
        ),
    ]
