# Generated by Django 5.2.6 on 2025-11-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_deposithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='blocked_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Blocked Funds'),
        ),
    ]
