# Generated by Django 5.2.3 on 2025-09-05 17:17

import modules.core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(help_text='Indicates whether the ticker is actively traded.', verbose_name='Active')),
                ('cik', models.CharField(blank=True, help_text='Central Index Key assigned by the SEC.', max_length=20, null=True, verbose_name='CIK')),
                ('composite_figi', models.CharField(blank=True, help_text='Composite Financial Instrument Global Identifier.', max_length=20, null=True, verbose_name='Composite FIGI')),
                ('currency_name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency Symbol')),
                ('base_currency_symbol', models.CharField(blank=True, help_text='Symbol of the base currency for FX or crypto tickers.', max_length=10, null=True, verbose_name='Base Currency Symbol')),
                ('base_currency_name', models.CharField(blank=True, help_text='Name of the base currency for FX or crypto tickers.', max_length=50, null=True, verbose_name='Base Currency Name')),
                ('locale', models.CharField(choices=[('us', 'United States'), ('global', 'Global')], help_text="Locale where the ticker is traded, e.g. 'US'.", max_length=50, verbose_name='Locale')),
                ('market', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('fx', 'Foreign Exchange'), ('otc', 'Over-the-Counter'), ('indices', 'Indices')], max_length=50, verbose_name='Market')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('primary_exchange', models.CharField(blank=True, help_text='Code of the primary exchange where the ticker is traded.', max_length=50, null=True, verbose_name='Primary Exchange')),
                ('share_class_figi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Share Class FIGI')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Ticker Symbol')),
                ('type', models.CharField(blank=True, help_text="Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.", max_length=50, null=True, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ticker_root', models.CharField(blank=True, help_text='Base symbol for related tickers.', max_length=50, null=True, verbose_name='Ticker Root')),
                ('ticker_suffix', models.CharField(blank=True, help_text='Suffix for ticker if applicable.', max_length=50, null=True, verbose_name='Ticker Suffix')),
                ('homepage_url', models.URLField(blank=True, null=True, verbose_name='Homepage URL')),
                ('list_date', models.DateField(blank=True, help_text='Date when the ticker was first listed.', null=True, verbose_name='List Date')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Market Cap')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('share_class_shares_outstanding', models.BigIntegerField(blank=True, help_text='Number of shares outstanding for this share class.', null=True, verbose_name='Shares Outstanding (Share Class)')),
                ('sic_code', models.CharField(blank=True, help_text='Standard Industrial Classification code.', max_length=10, null=True, verbose_name='SIC Code')),
                ('sic_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIC Description')),
                ('total_employees', models.IntegerField(blank=True, null=True, verbose_name='Total Employees')),
                ('weighted_shares_outstanding', models.BigIntegerField(blank=True, null=True, verbose_name='Weighted Shares Outstanding')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('icon_polygon_url', models.URLField(blank=True, null=True, verbose_name='Icon Polygon URL')),
                ('logo_polygon_url', models.URLField(blank=True, null=True, verbose_name='Logo Polygon URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=modules.core.utils.UploadTo('instruments/icons/'), verbose_name='Icon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=modules.core.utils.UploadTo('instruments/logos/'), verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['ticker'],
            },
        ),
    ]
