# Generated by Django 5.2.3 on 2025-08-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='locale',
            field=models.CharField(choices=[('us', 'United States'), ('global', 'Global')], help_text="Locale where the ticker is traded, e.g. 'US'.", max_length=50, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('fx', 'Foreign Exchange'), ('otc', 'Over-the-Counter'), ('indices', 'Indices')], max_length=50, verbose_name='Market'),
        ),
    ]
