# Generated by Django 5.1.3 on 2025-05-28 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Company Name"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Industry"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
            ],
            options={
                "verbose_name": "Company Details",
                "verbose_name_plural": "Company Details",
            },
        ),
        migrations.CreateModel(
            name="IndexDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Index Name"
                    ),
                ),
                (
                    "fund_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Fund Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Index Details",
                "verbose_name_plural": "Index Details",
            },
        ),
        migrations.AddField(
            model_name="instrument",
            name="details_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Details ID"),
        ),
        migrations.AddField(
            model_name="instrument",
            name="details_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("app_label", "instruments"),
                    ("model__in", ["companydetails", "indexdetails"]),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instruments",
                to="contenttypes.contenttype",
                verbose_name="Details Type",
            ),
        ),
    ]
