# Generated by Django 5.2.3 on 2025-08-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_v3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='last_updated_utc',
        ),
    ]
