# Generated by Django 5.2.3 on 2025-09-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_locale_alter_instrument_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='instrument',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='instruments/icons/', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='icon_polygon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Icon Polygon URL'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='instruments/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='logo_polygon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Logo Polygon URL'),
        ),
    ]
