# Generated by Django 5.2.6 on 2025-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Polish Description'),
        ),
    ]
