# Generated by Django 5.2.3 on 2025-08-02 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_companydetails_indexdetails_instrument_details_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ticker', models.CharField(unique=True)),
                ('ticker_type', models.CharField()),
                ('delisted', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField()),
                ('logo_url', models.URLField()),
                ('homepage_url', models.URLField()),
                ('address1', models.CharField()),
                ('address2', models.CharField()),
                ('city', models.CharField()),
                ('postal_code', models.CharField()),
                ('state', models.CharField()),
                ('currency_name', models.CharField()),
                ('market', models.CharField()),
                ('market_cap', models.DecimalField(decimal_places=15, max_digits=30)),
                ('phone_number', models.CharField()),
                ('sector', models.CharField()),
                ('total_employess', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
