# Generated by Django 5.2.3 on 2025-08-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrumentv2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentv2',
            name='address2',
        ),
    ]
