# Generated by Django 5.2.3 on 2025-09-05 16:51

import modules.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_remove_instrument_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=modules.core.utils.UploadTo('instruments/icons/'), verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=modules.core.utils.UploadTo('instruments/logos/'), verbose_name='Logo'),
        ),
    ]
