# Generated by Django 5.2.3 on 2025-08-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_remove_instrumentv2_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentv2',
            old_name='address1',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='total_employess',
            field=models.IntegerField(null=True),
        ),
    ]
