# Generated by Django 5.2.3 on 2025-08-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_rename_address1_instrumentv2_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentv2',
            name='address',
        ),
        migrations.RemoveField(
            model_name='instrumentv2',
            name='city',
        ),
        migrations.RemoveField(
            model_name='instrumentv2',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='instrumentv2',
            name='state',
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='currency_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='homepage_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='market',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='market_cap',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='phone_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='sector',
            field=models.CharField(null=True),
        ),
    ]
