# Generated by Django 5.2.3 on 2025-08-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_remove_instrumentv2_address_remove_instrumentv2_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentv2',
            name='icon_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='instrumentv2',
            name='logo_url',
            field=models.URLField(null=True),
        ),
    ]
