# Generated by Django 5.2.3 on 2025-08-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_alter_instrumentv2_icon_url_and_more'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
        migrations.DeleteModel(
            name='IndexDetails',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
