# Generated by Django 5.2.3 on 2025-08-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_delete_companydetails_delete_indexdetails_and_more'),
        ('investors', '0002_alter_investor_watching_instruments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentV2',
            new_name='Instrument',
        ),
    ]
