# Generated by Django 5.1.3 on 2025-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clerk_role",
            field=models.CharField(default="investor", max_length=50),
        ),
    ]
