# Generated by Django 5.1.3 on 2025-05-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_clerk_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_image",
            field=models.BooleanField(default=False, verbose_name="Has Image"),
        ),
        migrations.AddField(
            model_name="user",
            name="image_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Profile Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="clerk_role",
            field=models.CharField(
                default="investor", max_length=50, verbose_name="Clerk Role"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Last name"
            ),
        ),
    ]
