# Generated by Django 5.2.2 on 2025-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
