# Generated by Django 5.2.3 on 2025-09-07 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('instruments', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('volume_processed', models.IntegerField(default=0)),
                ('is_buy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('detail_id', models.IntegerField()),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
            options={
                'indexes': [models.Index(fields=['detail_type', 'detail_id'], name='orders_orde_detail__026320_idx')],
            },
        ),
    ]
