# Generated by Django 5.2.6 on 2025-09-28 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('instruments', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Volume')),
                ('volume_processed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Volume Processed')),
                ('is_buy', models.BooleanField(verbose_name='Is Buy')),
            ],
            options={
                'verbose_name': 'Market Order',
                'verbose_name_plural': 'Market Orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('detail_id', models.UUIDField()),
                ('detail_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'orders'), ('model', 'marketorder')), on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contenttypes.contenttype')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='investors.investor', verbose_name='Investor')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='instruments.instrument', verbose_name='Ticker')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'indexes': [models.Index(fields=['detail_type', 'detail_id'], name='orders_orde_detail__026320_idx')],
            },
        ),
    ]
