# Generated by Django 5.2.6 on 2025-11-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketorder',
            name='blocked_funds',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=30, verbose_name='Blocked Funds'),
        ),
    ]
