# Generated by Django 5.2.8 on 2025-11-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_marketorder_blocked_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='blocked_funds',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=30, verbose_name='Blocked Funds'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='volume',
            field=models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='volume_processed',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Volume Processed'),
        ),
    ]
