# Generated by Django 5.2.6 on 2025-11-09 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0003_alter_marketorder_blocked_funds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Volume')),
                ('volume_processed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Volume Processed')),
                ('is_buy', models.BooleanField(verbose_name='Is Buy')),
                ('limit_price', models.DecimalField(decimal_places=8, max_digits=30, verbose_name='Limit Price')),
                ('blocked_funds', models.DecimalField(decimal_places=2, default='0', max_digits=30, verbose_name='Blocked Funds')),
            ],
            options={
                'verbose_name': 'Limit Order',
                'verbose_name_plural': 'Limit Orders',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='detail_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'orders'), ('model__in', ['marketorder', 'limitorder'])), on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contenttypes.contenttype'),
        ),
    ]
