# Generated by Django 5.2.6 on 2025-10-16 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('threshold_type', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10, verbose_name='Threshold Type')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Threshold Value')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument', verbose_name='Instrument')),
                ('notification_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationconfig')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor', verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'unique_together': {('instrument', 'threshold_type', 'threshold_value')},
            },
        ),
    ]
