# Generated by Django 5.2.3 on 2025-08-22 00:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(blank=True, help_text='Indicates whether the ticker is actively traded.', null=True, verbose_name='Active')),
                ('cik', models.CharField(blank=True, help_text='Central Index Key assigned by the SEC.', max_length=20, null=True, verbose_name='CIK')),
                ('composite_figi', models.CharField(blank=True, help_text='Composite Financial Instrument Global Identifier.', max_length=20, null=True, verbose_name='Composite FIGI')),
                ('currency_name', models.CharField(blank=True, help_text='Full name of the currency.', max_length=50, null=True, verbose_name='Currency Name')),
                ('currency_symbol', models.CharField(blank=True, help_text='Currency ISO symbol.', max_length=10, null=True, verbose_name='Currency Symbol')),
                ('base_currency_symbol', models.CharField(blank=True, help_text='Symbol of the base currency for FX or crypto tickers.', max_length=10, null=True, verbose_name='Base Currency Symbol')),
                ('base_currency_name', models.CharField(blank=True, help_text='Name of the base currency for FX or crypto tickers.', max_length=50, null=True, verbose_name='Base Currency Name')),
                ('delisted_utc', models.DateTimeField(blank=True, help_text='The date and time when the ticker was delisted.', null=True, verbose_name='Delisted Date (UTC)')),
                ('last_updated_utc', models.DateTimeField(blank=True, help_text='The date and time when the ticker data was last updated.', null=True, verbose_name='Last Updated (UTC)')),
                ('locale', models.CharField(choices=[('us', 'United States'), ('global', 'Global')], help_text="Locale where the ticker is traded, e.g. 'US'.", max_length=10, verbose_name='Locale')),
                ('market', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('fx', 'Foreign Exchange'), ('otc', 'Over-the-Counter'), ('indices', 'Indices')], help_text="Market type, e.g. 'stocks', 'crypto', 'fx'.", max_length=20, verbose_name='Market')),
                ('name', models.CharField(help_text='Full name of the company or instrument.', max_length=255, verbose_name='Company Name')),
                ('primary_exchange', models.CharField(blank=True, help_text='Code of the primary exchange where the ticker is traded.', max_length=50, null=True, verbose_name='Primary Exchange')),
                ('share_class_figi', models.CharField(blank=True, help_text='Share class-specific FIGI.', max_length=20, null=True, verbose_name='Share Class FIGI')),
                ('ticker', models.CharField(db_index=True, help_text="Unique ticker symbol, e.g. 'AAPL'.", max_length=20, unique=True, verbose_name='Ticker Symbol')),
                ('type', models.CharField(blank=True, help_text="Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.", max_length=50, null=True, verbose_name='Type')),
                ('source_feed', models.CharField(blank=True, help_text='Indicates the data source feed.', max_length=100, null=True, verbose_name='Source Feed')),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Tickers',
                'ordering': ['ticker'],
            },
        ),
    ]
