# Generated by Django 5.2.3 on 2025-08-22 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_v3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(help_text='Indicates whether the ticker is actively traded.', verbose_name='Active')),
                ('cik', models.CharField(blank=True, help_text='Central Index Key assigned by the SEC.', max_length=20, null=True, verbose_name='CIK')),
                ('composite_figi', models.CharField(blank=True, help_text='Composite Financial Instrument Global Identifier.', max_length=20, null=True, verbose_name='Composite FIGI')),
                ('currency_name', models.CharField(help_text='Full name of the currency.', max_length=50, verbose_name='Currency Name')),
                ('currency_symbol', models.CharField(blank=True, help_text='Currency ISO symbol.', max_length=10, null=True, verbose_name='Currency Symbol')),
                ('base_currency_symbol', models.CharField(blank=True, help_text='Symbol of the base currency for FX or crypto tickers.', max_length=10, null=True, verbose_name='Base Currency Symbol')),
                ('base_currency_name', models.CharField(blank=True, help_text='Name of the base currency for FX or crypto tickers.', max_length=50, null=True, verbose_name='Base Currency Name')),
                ('delisted_utc', models.DateTimeField(blank=True, help_text='The date and time when the ticker was delisted.', null=True, verbose_name='Delisted Date (UTC)')),
                ('last_updated_utc', models.DateTimeField(blank=True, help_text='The date and time when the ticker data was last updated.', null=True, verbose_name='Last Updated (UTC)')),
                ('locale', models.CharField(choices=[('us', 'United States'), ('global', 'Global')], help_text="Locale where the ticker is traded, e.g. 'US'.", max_length=10, verbose_name='Locale')),
                ('market', models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('fx', 'Foreign Exchange'), ('otc', 'Over-the-Counter'), ('indices', 'Indices')], help_text="Market type, e.g. 'stocks', 'crypto', 'fx'.", max_length=20, verbose_name='Market')),
                ('name', models.CharField(help_text='Full name of the company or instrument.', max_length=255, verbose_name='Company Name')),
                ('primary_exchange', models.CharField(blank=True, help_text='Code of the primary exchange where the ticker is traded.', max_length=50, null=True, verbose_name='Primary Exchange')),
                ('share_class_figi', models.CharField(blank=True, help_text='Share class-specific FIGI.', max_length=20, null=True, verbose_name='Share Class FIGI')),
                ('ticker', models.CharField(db_index=True, help_text="Unique ticker symbol, e.g. 'AAPL'.", max_length=20, unique=True, verbose_name='Ticker Symbol')),
                ('type', models.CharField(blank=True, help_text="Security type, e.g. 'CS' (Common Stock), 'ETF', 'Crypto'.", max_length=50, null=True, verbose_name='Type')),
                ('source_feed', models.CharField(blank=True, help_text='Indicates the data source feed.', max_length=100, null=True, verbose_name='Source Feed')),
                ('description', models.TextField(blank=True, help_text='Business description of the company.', null=True, verbose_name='Description')),
                ('ticker_root', models.CharField(blank=True, help_text='Base symbol for related tickers.', max_length=50, null=True, verbose_name='Ticker Root')),
                ('ticker_suffix', models.CharField(blank=True, help_text='Suffix for ticker if applicable.', max_length=50, null=True, verbose_name='Ticker Suffix')),
                ('homepage_url', models.URLField(blank=True, help_text='Company homepage URL.', null=True, verbose_name='Homepage URL')),
                ('list_date', models.DateField(blank=True, help_text='Date when the ticker was first listed.', null=True, verbose_name='List Date')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Market capitalization.', max_digits=20, null=True, verbose_name='Market Cap')),
                ('phone_number', models.CharField(blank=True, help_text='Company contact phone number.', max_length=30, null=True, verbose_name='Phone Number')),
                ('share_class_shares_outstanding', models.BigIntegerField(blank=True, help_text='Number of shares outstanding for this share class.', null=True, verbose_name='Shares Outstanding (Share Class)')),
                ('sic_code', models.CharField(blank=True, help_text='Standard Industrial Classification code.', max_length=10, null=True, verbose_name='SIC Code')),
                ('sic_description', models.CharField(blank=True, help_text='Description of the SIC code.', max_length=255, null=True, verbose_name='SIC Description')),
                ('total_employees', models.IntegerField(blank=True, help_text='Total number of employees.', null=True, verbose_name='Total Employees')),
                ('weighted_shares_outstanding', models.BigIntegerField(blank=True, help_text='Weighted shares outstanding.', null=True, verbose_name='Weighted Shares Outstanding')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Icon URL')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('accent_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Accent Color')),
                ('light_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Light Color')),
                ('dark_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dark Color')),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Tickers',
                'ordering': ['ticker'],
            },
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
