# Generated by Django 5.2.3 on 2025-08-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_v3', '0002_instrument_delete_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['ticker'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='currency_name',
            field=models.CharField(max_length=50, verbose_name='Currency Name'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency Symbol'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='homepage_url',
            field=models.URLField(blank=True, null=True, verbose_name='Homepage URL'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_updated_utc',
            field=models.DateTimeField(blank=True, help_text='When the ticker data was last updated in Polygon.', null=True, verbose_name='Last Updated (UTC)'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='market',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('crypto', 'Crypto'), ('fx', 'Foreign Exchange'), ('otc', 'Over-the-Counter'), ('indices', 'Indices')], max_length=20, verbose_name='Market'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Market Cap'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='share_class_figi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Share Class FIGI'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='sic_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SIC Description'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Ticker Symbol'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='total_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Employees'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='weighted_shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Weighted Shares Outstanding'),
        ),
    ]
