# Generated by Django 5.2.3 on 2025-08-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments_v3', '0003_alter_instrument_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='dark_color',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='delisted_utc',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='light_color',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='source_feed',
        ),
    ]
