# Generated by Django 5.2.6 on 2025-09-28 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=255, unique=True, verbose_name='Clerk ID')),
                ('balance', models.DecimalField(decimal_places=2, default='0', max_digits=30)),
                ('watching_instruments', models.ManyToManyField(blank=True, to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('volume', models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Quantity of instrument held')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument', verbose_name='Instrument held')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor', verbose_name='Owning investor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountValueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of the snapshot')),
                ('value', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total account value')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor', verbose_name='Associated investor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
