# Generated by Django 5.2.6 on 2025-10-05 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountValueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Of The Snapshot')),
                ('value', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Total Account Value')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor', verbose_name='Associated Investor')),
            ],
            options={
                'verbose_name': 'Account Value Snapshot',
                'verbose_name_plural': 'Account Value Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
