# Generated by Django 5.2.3 on 2025-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='clerk_id',
            field=models.CharField(default='id', max_length=255, unique=True, verbose_name='Clerk ID'),
            preserve_default=False,
        ),
    ]
