# Generated by Django 5.2.3 on 2025-09-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='volume',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
