# Generated by Django 5.2.3 on 2025-09-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
