# Generated by Django 5.2.6 on 2025-10-07 06:25

import modules.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvaluesnapshot',
            name='timestamp',
            field=models.DateTimeField(default=modules.core.utils.get_local_datetime, verbose_name='Datetime Of The Snapshot'),
        ),
    ]
