# Generated by Django 5.2.6 on 2025-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='language',
            field=models.CharField(default='en', help_text="User's preferred language (e.g., 'en', 'pl')", max_length=10, verbose_name='Language'),
        ),
    ]
