# Generated by Django 5.2.3 on 2025-08-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='user',
        ),
        migrations.AddField(
            model_name='investor',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Clerk ID'),
        ),
    ]
