# Generated by Django 5.2.3 on 2025-08-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_delete_companydetails_delete_indexdetails_and_more'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='watching_instruments',
            field=models.ManyToManyField(blank=True, to='instruments.instrumentv2'),
        ),
    ]
