# Generated by Django 5.2.6 on 2025-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investor_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='buffer_money',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=30, verbose_name='Buffer Money'),
        ),
    ]
