# Generated by Django 5.2.3 on 2025-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_investor_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='EXP'),
        ),
    ]
