# Generated by Django 5.2.3 on 2025-09-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0002_alter_investor_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=30),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('pk', models.CompositePrimaryKey('investor', 'ticker', blank=True, editable=False, primary_key=True, serialize=False)),
                ('volume', models.DecimalField(decimal_places=15, max_digits=30)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
        ),
    ]
