# Generated by Django 5.2.3 on 2025-09-03 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('investors', '0003_investor_exp'), ('investors', '0004_alter_investor_exp')]

    dependencies = [
        ('investors', '0002_alter_investor_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='exp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='EXP'),
        ),
    ]
