# Generated by Django 5.2.6 on 2025-09-26 17:49
# Squashed migration combining 0003_investor_base_model and 0004_investor_language

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0002_alter_investor_clerk_id'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE investors_investor CASCADE;',
            reverse_sql='',
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('clerk_id', models.CharField(max_length=255, unique=True, verbose_name='Clerk ID')),
                ('language', models.CharField(default='en', help_text="User's preferred language (e.g., 'en', 'pl')", max_length=10, verbose_name='Language')),
            ],
        ),
    ]