# Generated by Django 5.2.3 on 2025-09-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0002_alter_asset_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument'),
        ),
    ]
