# Generated by Django 5.2.3 on 2025-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_alter_asset_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='volume',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
