# Generated by Django 5.2.8 on 2025-11-07 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_investor_blocked_funds'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(max_length=50, verbose_name='Notification Type')),
                ('message_en', models.TextField(verbose_name='Notification Message (english)')),
                ('message_pl', models.TextField(verbose_name='Notification Message (polish)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investors.investor', verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Notification History',
                'verbose_name_plural': 'Notification Histories',
                'ordering': ['-sent_at'],
            },
        ),
    ]
