# Generated by Django 5.2.6 on 2025-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_lang', '0002_alter_graph_graph_data_alter_graph_raw_graph_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='name',
            field=models.CharField(default='hehexd', max_length=100),
            preserve_default=False,
        ),
    ]
