# Generated by Django 5.2.6 on 2025-11-10 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('graph_lang', '0003_graph_name'),
        ('instruments', '0003_instrument_description_pl'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('message', models.TextField()),
                ('format', models.CharField(choices=[('push', 'push'), ('mail', 'mail')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuySellEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_buy', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=15, max_digits=30)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('effect_id', models.UUIDField()),
                ('effect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph_lang.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
