# Generated by Django 5.2.6 on 2025-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_lang', '0006_graph_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
