# Generated by Django 5.2.6 on 2025-11-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_lang', '0007_graph_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyselleffect',
            name='action_price',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
