# Generated by Django 5.2.6 on 2025-09-28 13:42

import django.db.models.deletion
import modules.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(default=modules.core.utils.get_local_datetime)),
                ('volume', models.DecimalField(decimal_places=15, max_digits=30)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_buy', models.BooleanField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
        ),
    ]
