# Generated by Django 5.2.3 on 2025-09-21 12:18

import django.db.models.deletion
import modules.core.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('transaction_time', models.DateTimeField(default=modules.core.utils.get_local_datetime)),
                ('volume', models.DecimalField(decimal_places=15, max_digits=30)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_buy', models.BooleanField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHelper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('volume', models.DecimalField(decimal_places=15, max_digits=30)),
                ('buy_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='transactions.transaction')),
                ('sell_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
