# Generated by Django 5.2.3 on 2025-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='volume',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transactionhelper',
            name='volume',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
