# Generated by Django 5.2.6 on 2025-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the ticker is actively traded.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='currency_name',
            field=models.CharField(default='usd', max_length=50, verbose_name='Currency Name'),
        ),
    ]
