# Generated by Django 5.2.6 on 2025-09-25 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('investors', '0003_investor_base_model_and_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('endpoint', models.URLField(max_length=512, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256DH Key')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth Key')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor', verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_email', models.BooleanField(default=False, verbose_name='Send Email')),
                ('is_push', models.BooleanField(default=True, verbose_name='Send Push')),
                ('is_websocket', models.BooleanField(default=True, verbose_name='Send WebSocket')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('threshold_type', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=10, verbose_name='Threshold Type')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Threshold Value')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument', verbose_name='Instrument')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor', verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'unique_together': {('investor', 'instrument', 'threshold_type', 'threshold_value')},
            },
        ),
    ]
