# Generated by Django 5.2.6 on 2025-11-01 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_investor_buffer_money'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('price_alert', 'Price Alert'), ('order', 'Order'), ('transaction', 'Transaction'), ('system', 'System')], default='system', max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is Seen')),
                ('related_object_id', models.CharField(blank=True, help_text='ID of the related object (e.g., price alert ID, order ID)', max_length=255, null=True, verbose_name='Related Object ID')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of the related object (e.g., 'price_alert', 'order')", max_length=50, null=True, verbose_name='Related Object Type')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investors.investor', verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investor', '-created_at'], name='notificatio_investo_7bab8b_idx'), models.Index(fields=['investor', 'is_seen', '-created_at'], name='notificatio_investo_06044f_idx')],
            },
        ),
    ]
