# Generated by Django 5.2.6 on 2025-10-31 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('raw_graph_data', models.TextField()),
                ('graph_data', models.TextField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
