# Generated by Django 5.2.6 on 2025-11-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_lang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='graph',
            name='raw_graph_data',
            field=models.JSONField(),
        ),
    ]
