# Generated by Django 5.2.6 on 2025-11-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_lang', '0004_notificationeffect_buyselleffect_grapheffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='grapheffect',
            name='success',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
