# Generated by Django 5.2.6 on 2025-11-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_lang', '0005_grapheffect_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
